public class Futureexample {
    @future
    public static void testusecases(){
        system.debug('futureexample');
        System.enqueueJob(new Queueablexample ());

        //Batchexample be=new Batchexample();
//id batchinstanceid = database.executeBatch(be);
//SchedulerClass sc=new SchedulerClass();
//System.schedule('TestSchedulerClass Job1', '0 0 * * * ?', new SchedulerClass());


    }
}