public class Queueablexample implements Queueable {
    public void execute(QueueableContext context) {
        Account a = new Account(Name='ambativenkat',Phone='(415) 555-1212');
        insert a;   
        //Futureexample.testusecases();
        //SchedulerClass sc=new SchedulerClass();
//System.schedule('TestSchedulerClass Job1', '0 0 * * * ?', new SchedulerClass());

        //Batchexample atr=new Batchexample();
//id batchinstanceid = database.executeBatch(atr);

    }
}