global class SchedulerClass implements Schedulable{
global void execute(SchedulableContext sc){  
 //Batchexample atr=new Batchexample();
//id batchinstanceid = database.executeBatch(atr); 
    system.debug('batchscheduling');
//ID jobID = System.enqueueJob(new Queueablexample2());
//Futureexample.testusecases();

//System.schedule('TestSchedulerClass Job1', '0 0 * * * ?', new SchedulerClass2());

	}
}